name: Release Build 🚀

on:
  push: 
    tag:
    - "v*"

jobs:
  Checks:
    uses: ./.github/workflows/check.yaml
    secrets: inherit

  CliBuild:
    needs: Checks
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Python Setup
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      
      - name: Dependency Install
        run: pip install -r requirements.txt

      - name: Package CLI
        run: pyinstaller --onefile notoil.py

      - name: Test Cli
        run: ./dist/notoil --help

      - name: Push Artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/notoil